version: '2'

networks:
  default:

services:
  php:
    build:
      args:
        PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
        PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE}
        PHP_ERROR_REPORTING: ${PHP_ERROR_REPORTING}
        PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
        PHP_LOG_ERRORS: ${PHP_LOG_ERRORS}
      context: .
    volumes:
      - ./:/app:cached
    links:
      - mysql

  nginx:
    build: docker/nginx
    ports:
      - '80:80'
    volumes_from:
      - php
    links:
      - php

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
